# Generated by Django 5.1.2 on 2024-10-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reservations/pdfs/'),
        ),
    ]
